spring.application.name=GuildOfPioneersBackend

app.timezone=${APP_TIMEZONE:UTC+8}
app.default-avatar=${APP_DEFAULT_AVATAR:./default_avatar.jpg}
app.default-avatar-enabled=${APP_DEFAULT_AVATAR_ENABLED:true}
app.seed-data=${APP_SEED_DATA:true}
app.admin-seed=${APP_ADMIN_SEED:true}
app.admin-password=${APP_ADMIN_PASSWORD:password123}

app.storage.type=${STORAGE_TYPE:s3}
app.storage.endpoint=${S3_ENDPOINT:http://localhost:9000}
app.storage.region=${S3_REGION:us-east-1}
app.storage.access-key=${S3_ACCESS_KEY:}
app.storage.secret-key=${S3_SECRET_KEY:}
app.storage.bucket=${S3_BUCKET:guild}
app.storage.path-style-access=${S3_PATH_STYLE:true}
app.storage.create-bucket=${S3_CREATE_BUCKET:true}

spring.servlet.multipart.max-file-size=${APP_MAX_AVATAR_SIZE:5MB}
spring.servlet.multipart.max-request-size=6MB

spring.datasource.url=jdbc:postgresql://localhost:5432/guild
spring.datasource.username=${DB_USERNAME:guild}
spring.datasource.password=${DB_PASSWORD:guild}

spring.jpa.hibernate.ddl-auto=none

spring.flyway.locations=classpath:db/migration
