spring.application.name=GuildOfPioneersBackend

app.timezone=${APP_TIMEZONE:UTC+8}

spring.datasource.url=jdbc:postgresql://localhost:5432/guild
spring.datasource.username=${DB_USERNAME:guild}
spring.datasource.password=${DB_PASSWORD:guild}

spring.jpa.hibernate.ddl-auto=none

spring.flyway.locations=classpath:db/migration
