app.timezone=${APP_TIMEZONE:UTC+8}
app.upload-dir=${APP_UPLOAD_DIR:./uploads}
app.seed-data=${APP_SEED_DATA:false}

spring.servlet.multipart.max-file-size=${APP_MAX_AVATAR_SIZE:5MB}
spring.servlet.multipart.max-request-size=6MB

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.flyway.locations=classpath:db/migration
